{
 "title": "Limits and Requests",
 "tags": [
  "k8s",
  "resources",
  "parm_namespace",
  "view_pod"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "role",
    "query": "up{kubernetes_io_role!=\"\"}"
   },
   { "name": "top", "query": "5,10,20,100" },
   {
    "name": "namespace",
    "query": "kube_pod_container_status_running"
   },
   {
    "name": "pod_name",
    "label": "pod",
    "query": "kube_pod_container_status_running{namespace=~\"$namespace\"}"
   },
   {
    "name": "container_name",
    "label": "container",
    "query": "kube_pod_container_status_running{namespace=~\"$namespace\",pod=~\"$pod_name.*\"}"
   },
   {
    "name": "_interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod=~\"$pod_name.*\",container_name=~\"$container_name\"})"
    }
   ]
  },
  {
   "title": "Requested Memory Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod=~\"$pod_name.*\"}) / sum (kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod_name.*\"}) * 100",
     "legendFormat": "Request"
    },
    {
     "expr": "sum (container_memory_usage_bytes{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod=~\"$pod_name.*\"}) / sum (kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod_name.*\"}) * 100",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\",container_name=~\"$container_name\"}[$_interval]))"
    }
   ]
  },
  {
   "title": "Requested CPU Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\",container_name=~\"$container_name\"}[$_interval])) / sum (kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",pod=~\"$pod_name.*\"}) * 100",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\",container_name=~\"$container_name\"}[$_interval]))/ sum (kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\",pod=~\"$pod_name.*\"}) * 100",
     "legendFormat": "Limits"
    }
   ]
  }
 ]
}