{
 "title": "Okteto Node State",
 "tags": [
  "k8s",
  "resources",
  "node",
  "okteto"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "role",
    "query": "up{kubernetes_io_role!=\"\"}"
   },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "_interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$_interval])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Avg (Last min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pod pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (kubelet_running_pod_count{kubernetes_io_hostname=~\"^$Node$\"}) / ((sum (kube_node_status_allocatable_pods) / sum (kube_node_info)) * sum (kubelet_node_name{kubernetes_io_hostname=~\"^$Node$\"}))) * 100"
    }
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_info{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Node Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{node=~\"^$Node$\",condition=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{node=~\"^$Node$\",condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_spec_unschedulable{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{node=~\"^$Node$\",condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Network Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{node=~\"^$Node$\",condition=\"NetworkUnavailable\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{node=~\"^$Node$\",condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node PID Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{node=~\"^$Node$\",condition=\"PIDPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Frequent Containerd Restart",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{node=~\"^$Node$\",condition=\"FrequentContainerdRestart\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Pods" }
   ],
   "targets": [
    { "expr": "kubelet_running_pod_count", "legendFormat": "kubelet - {{instance}}" }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Active Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{kubernetes_node=~\"^$Node$\",phase=\"Running\"}) / sum (kube_pod_status_phase{kubernetes_node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{kubernetes_node=~\"^$Node$\"}) "
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{kubernetes_node=~\"^$Node$\",phase=\"Running\"}) "
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{kubernetes_node=~\"^$Node$\",phase!=\"Running\"}) "
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{kubernetes_node=~\"^$Node$\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{kubernetes_node=~\"^$Node$\",phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{kubernetes_node=~\"^$Node$\",phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{kubernetes_node=~\"^$Node$\",phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{kubernetes_node=~\"^$Node$\"}[2m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{kubernetes_node=~\"^$Node$\"}[5m]))"
    }
   ]
  }
 ]
}