{
 "title": "Kubernetes resource usage per namespace and podas",
 "tags": [
  "k8s",
  "resources",
  "parm_namespace",
  "view_pod"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "role",
    "query": "up{kubernetes_io_role!=\"\"}"
   },
   { "name": "top", "query": "5,10,20,100" },
   {
    "name": "namespace",
    "query": "kube_pod_container_status_running"
   },
   {
    "name": "pod_name",
    "label": "pod",
    "query": "kube_pod_container_status_running{namespace=~\"$namespace\"}"
   },
   {
    "name": "container_name",
    "label": "container",
    "query": "kube_pod_container_status_running{namespace=~\"$namespace\",pod=~\"$pod_name.*\"}"
   },
   {
    "name": "_interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Containers CPU and MEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "top$top container CPU usage  for ns=\"$namespace\" (pod_name=\"$pod_name\",container_name=\"$container_name\")",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum(rate(container_cpu_usage_seconds_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\",container_name=~\"$container_name\"}[$_interval])) without (cpu)) > 1e-3",
     "legendFormat": "{{cluster}} - {{ pod_name }}/{{ container_name }}"
    }
   ]
  },
  {
   "title": "top$top container MEM usage  for ns=\"$namespace\" (pod_name=\"$pod_name\",container_name=\"$container_name\")",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($top, container_memory_working_set_bytes{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\",container_name=~\"$container_name\"})",
     "legendFormat": "{{cluster}} - {{ pod_name }}/{{ container_name }}"
    }
   ]
  },
  { "title": "Containers I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "top$top container IO +R -W for ns=\"$namespace\" (pod_name=\"$pod_name\",container_name=\"$container_name\") [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum(rate(container_fs_reads_bytes_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\",container_name=~\"$container_name\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{ pod_name }}/{{ container_name }}"
    },
    {
     "expr": "- topk($top, sum(rate(container_fs_writes_bytes_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\",container_name=~\"$container_name\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{ pod_name }}/{{ container_name }}"
    }
   ]
  },
  {
   "title": "top$top container IO +R -W ns=\"$namespace\" (pod_name=\"$pod_name\",container_name=\"$container_name\") [iops]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum(rate(container_fs_reads_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\",container_name=~\"$container_name\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{ pod_name}}/{{ container_name }}"
    },
    {
     "expr": "- topk($top, sum(rate(container_fs_writes_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\",container_name=~\"$container_name\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{ pod_name}}/{{ container_name }}"
    }
   ]
  },
  { "title": "Pods Network traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "top$top Pod Network +RX -TX ns=\"$namespace\" (pod_name=\"$pod_name\") [Bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum(rate(container_network_receive_bytes_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{ pod_name}}"
    },
    {
     "expr": "- topk($top, sum(rate(container_network_transmit_bytes_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",container_name=~\"$container_name\",pod_name=~\"$pod_name.*\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{ pod_name}}"
    }
   ]
  },
  {
   "title": "top$top Pod Network +RX -TX ns=\"$namespace\" (pod_name=\"$pod_name\") [pkts/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum(rate(container_network_receive_packets_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{ pod_name }}"
    },
    {
     "expr": "- topk($top, sum(rate(container_network_transmit_packets_total{kubernetes_io_role=\"$role\",namespace=~\"$namespace\",pod_name=~\"$pod_name.*\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{ pod_name }}"
    }
   ]
  }
 ]
}